pipeline {
    agent { label 'docker-node' }
    stages {
        stage('1.build') {
            steps {
                sh '''
                docker build -f docker/Dockerfile  -t  harbor.oldboy.cn/web/ruoyi:backend_v1  .
                docker login  -u admin  -p Lidao996 harbor.oldboy.cn
                docker push  harbor.oldboy.cn/web/ruoyi:backend_v1
                docker rmi harbor.oldboy.cn/web/ruoyi:backend_v1
                docker image prune -f
                '''
            }
        }
        stage('2 .确认是否部署') {
            steps {
                input '是否继续进行部署'
            }
        }
        stage('3.deploy') {
            steps {
                sh '''
                ip_list=10.0.0.81
                for ip in $ip_list
                do
                   ssh  root@$ip  'docker ps -aq -f "name=ruoyi_backend*" |xargs docker rm -f  '
                   ssh  root@$ip  "docker run  -d  --name ruoyi_backend_v1  -p 8080:8080  harbor.oldboy.cn/web/ruoyi:backend_v1 "
                done
                '''
            }
        }
    }
}
